# Generated by Django 3.2.4 on 2022-12-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_slot_alter_user_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='months',
            field=models.CharField(max_length=200),
        ),
    ]
